
   # Name of this microservice
   spring.application.name=product-service

   # Port this service runs on
   server.port=8081

   # Where the database is
   spring.datasource.url=jdbc:mysql://localhost:3306/product_db
   spring.datasource.username=root

   # Load the password from a separate file that is NOT pushed to GitHub
   spring.config.import=optional:classpath:application-local.properties

   # Let Spring create and update tables automatically from our Java classes
   spring.jpa.hibernate.ddl-auto=update

   # Print the SQL that Spring runs, so we can learn from it
   spring.jpa.show-sql=true
